server:
  port: 8080
spring:
  application:
    name: gateway-ms
  cloud:
    gateway:
      discovery:
        locator:
          enabled: 'true'
      routes:
        - id: students-ms
          uri: lb://STUDENTS-MS
          predicates:
            - Path=/students/**

        - id: grades-ms
          uri: lb://GRADES-MS
          predicates:
            - Path=/grades/**
    loadbalancer:
      ribbon:
        enabled: 'false'
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id="${spring.application.name}:${server.port}"